{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-spam-lab.fullname" . }}-collector
  labels:
    {{- include "github-spam-lab.labels" . | nindent 4 }}
    component: collector
spec:
  type: ClusterIP
  selector:
    {{- include "github-spam-lab.selectorLabels" . | nindent 4 }}
    component: collector
  ports:
    - name: http-metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
{{- end }}

